//! #148 / #151 — Android "All files access" (MANAGE_EXTERNAL_STORAGE).
//!
//! Android's sandbox puts the app's only freely-readable folder under
//! `/Android/data/app.solomd/files`, which no file manager can browse on an
//! unrooted device — so a user's real vault (`…/Documents`, a Syncthing or
//! Dropbox folder) was unreachable, and files opened from a file manager had
//! to be *copied* into the sandbox instead of edited in place (#148 reporter).
//!
//! With MANAGE_EXTERNAL_STORAGE granted, `/storage/emulated/0/…` paths are
//! directly readable/writable by `std::fs`, so the whole existing path-based
//! stack (read_file / write_file / list_dir / watcher / AutoGit) works against
//! the user's actual folder with zero special-casing.
//!
//! The permission is special (not a normal runtime grant): it's checked with
//! `Environment.isExternalStorageManager()` and requested by launching a
//! system Settings screen. We do both from Rust via JNI — the app's Kotlin
//! tree is regenerated by `tauri android init` and gitignored, so a Kotlin
//! `@TauriPlugin` wouldn't survive a fresh checkout; committed Rust does.

/// Returns true when the app holds MANAGE_EXTERNAL_STORAGE (all-files access).
/// Always false off-Android (desktop uses ordinary filesystem access; the UI
/// only calls this on Android).
#[tauri::command]
pub fn android_has_all_files_access() -> bool {
    #[cfg(target_os = "android")]
    {
        imp::has_all_files_access().unwrap_or(false)
    }
    #[cfg(not(target_os = "android"))]
    {
        true
    }
}

/// Launch the system "All files access" settings screen for this app. The
/// grant happens in Settings (outside our process), so the frontend re-checks
/// `android_has_all_files_access` when the app resumes. No-op off-Android.
#[tauri::command]
pub fn android_request_all_files_access() -> Result<(), String> {
    #[cfg(target_os = "android")]
    {
        imp::request_all_files_access()
    }
    #[cfg(not(target_os = "android"))]
    {
        Ok(())
    }
}

#[cfg(target_os = "android")]
mod imp {
    use jni::objects::{JObject, JValue};
    use jni::JavaVM;

    /// Run `f` with an attached JNIEnv and the Activity object Tauri created.
    fn with_activity<T>(
        f: impl FnOnce(&mut jni::JNIEnv, &JObject) -> Result<T, jni::errors::Error>,
    ) -> Result<T, String> {
        // SAFETY: ndk-context hands back the VM + Activity pointers that the
        // Android runtime (and Tauri) already own for this process.
        let ctx = ndk_context::android_context();
        let vm = unsafe { JavaVM::from_raw(ctx.vm().cast()) }.map_err(|e| e.to_string())?;
        let activity = unsafe { JObject::from_raw(ctx.context().cast()) };
        let mut env = vm.attach_current_thread().map_err(|e| e.to_string())?;
        f(&mut env, &activity).map_err(|e| e.to_string())
    }

    pub fn has_all_files_access() -> Result<bool, String> {
        with_activity(|env, _activity| {
            // Environment.isExternalStorageManager() — static, added in API 30.
            let result = env
                .call_static_method(
                    "android/os/Environment",
                    "isExternalStorageManager",
                    "()Z",
                    &[],
                )?
                .z()?;
            Ok(result)
        })
    }

    pub fn request_all_files_access() -> Result<(), String> {
        with_activity(|env, activity| {
            // Intent(Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION)
            let action = env.new_string(
                "android.settings.MANAGE_APP_ALL_FILES_ACCESS_PERMISSION",
            )?;
            let intent = env.new_object(
                "android/content/Intent",
                "(Ljava/lang/String;)V",
                &[JValue::Object(&action)],
            )?;

            // uri = Uri.parse("package:" + activity.getPackageName())
            let pkg = env
                .call_method(activity, "getPackageName", "()Ljava/lang/String;", &[])?
                .l()?;
            let pkg_str: String = env.get_string((&pkg).into())?.into();
            let uri_string = env.new_string(format!("package:{pkg_str}"))?;
            let uri = env
                .call_static_method(
                    "android/net/Uri",
                    "parse",
                    "(Ljava/lang/String;)Landroid/net/Uri;",
                    &[JValue::Object(&uri_string)],
                )?
                .l()?;
            env.call_method(
                &intent,
                "setData",
                "(Landroid/net/Uri;)Landroid/content/Intent;",
                &[JValue::Object(&uri)],
            )?;

            // activity.startActivity(intent)
            env.call_method(
                activity,
                "startActivity",
                "(Landroid/content/Intent;)V",
                &[JValue::Object(&intent)],
            )?;
            Ok(())
        })
    }
}
