//! #148 / #151 — Android "All files access" (MANAGE_EXTERNAL_STORAGE).
//!
//! Android's sandbox puts the app's only freely-readable folder under
//! `/Android/data/app.solomd/files`, which no file manager can browse on an
//! unrooted device — so a user's real vault (`…/Documents`, a Syncthing or
//! Dropbox folder) was unreachable, and files opened from a file manager had
//! to be *copied* into the sandbox instead of edited in place (#148 reporter).
//!
//! With MANAGE_EXTERNAL_STORAGE granted, `/storage/emulated/0/…` paths are
//! directly readable/writable by `std::fs`, so the whole existing path-based
//! stack (read_file / write_file / list_dir / watcher / AutoGit) works against
//! the user's actual folder with zero special-casing.
//!
//! The permission is special (not a normal runtime grant): it's checked with
//! `Environment.isExternalStorageManager()` and requested by launching a
//! system Settings screen. We do both from Rust via JNI — the app's Kotlin
//! tree is regenerated by `tauri android init` and gitignored, so a Kotlin
//! `@TauriPlugin` wouldn't survive a fresh checkout; committed Rust does.

/// Returns true when the app holds MANAGE_EXTERNAL_STORAGE (all-files access).
/// Always false off-Android (desktop uses ordinary filesystem access; the UI
/// only calls this on Android).
#[tauri::command]
pub fn android_has_all_files_access() -> bool {
    #[cfg(target_os = "android")]
    {
        imp::has_all_files_access().unwrap_or(false)
    }
    #[cfg(not(target_os = "android"))]
    {
        true
    }
}

/// Launch the system "All files access" settings screen for this app. The
/// grant happens in Settings (outside our process), so the frontend re-checks
/// `android_has_all_files_access` when the app resumes. No-op off-Android.
#[tauri::command]
pub fn android_request_all_files_access() -> Result<(), String> {
    #[cfg(target_os = "android")]
    {
        imp::request_all_files_access()
    }
    #[cfg(not(target_os = "android"))]
    {
        Ok(())
    }
}

/// System-bar inset heights in **physical pixels** (status bar top,
/// navigation bar bottom).
#[derive(serde::Serialize, Default)]
pub struct SystemInsets {
    pub top: i32,
    pub bottom: i32,
}

/// #153 (mobile) — status-bar / nav-bar heights so the web layer can keep the
/// toolbar out from under the Android system bars.
///
/// Android 15 (targetSdk 35+) forces edge-to-edge and it can't be turned off,
/// so the WebView draws behind the status bar. The CSS `env(safe-area-inset-*)`
/// that would normally carry the inset returns **0** in Android's WebView
/// (unlike iOS WKWebView), so the toolbar rendered under the clock/battery and
/// became untappable. Reading the heights natively and injecting them as a CSS
/// var (see App.vue) sidesteps the broken `env()` entirely. Returns physical
/// px; the frontend divides by `devicePixelRatio` for CSS px. Zeroes
/// off-Android (desktop `env()` is 0 anyway → no-op).
#[tauri::command]
pub fn android_system_insets() -> SystemInsets {
    #[cfg(target_os = "android")]
    {
        imp::system_insets().unwrap_or_default()
    }
    #[cfg(not(target_os = "android"))]
    {
        SystemInsets::default()
    }
}

/// #148 (follow-up) — restart the app process.
///
/// MANAGE_EXTERNAL_STORAGE is granted in system Settings *outside* our process.
/// `Environment.isExternalStorageManager()` flips to true immediately, but the
/// app's shared-storage sandbox was bind-mounted when the process launched and
/// is **not** remounted on grant — so `std::fs` keeps returning EACCES on
/// `/storage/emulated/0` until the process is recreated. (The emulator masked
/// this because its shared storage is readable without the permission at all.)
/// So after the user grants, we relaunch (see `imp::restart_app`): start a
/// fresh-task launch intent while still foreground, then exit so a brand-new
/// process picks up the new mount. No-op off-Android.
#[tauri::command]
pub fn android_restart_app() -> Result<(), String> {
    #[cfg(target_os = "android")]
    {
        imp::restart_app()
    }
    #[cfg(not(target_os = "android"))]
    {
        Ok(())
    }
}

#[cfg(target_os = "android")]
mod imp {
    use jni::objects::{JObject, JValue};
    use jni::JavaVM;

    /// Run `f` with an attached JNIEnv and the Activity object Tauri created.
    fn with_activity<T>(
        f: impl FnOnce(&mut jni::JNIEnv, &JObject) -> Result<T, jni::errors::Error>,
    ) -> Result<T, String> {
        // SAFETY: ndk-context hands back the VM + Activity pointers that the
        // Android runtime (and Tauri) already own for this process.
        let ctx = ndk_context::android_context();
        let vm = unsafe { JavaVM::from_raw(ctx.vm().cast()) }.map_err(|e| e.to_string())?;
        let activity = unsafe { JObject::from_raw(ctx.context().cast()) };
        let mut env = vm.attach_current_thread().map_err(|e| e.to_string())?;
        f(&mut env, &activity).map_err(|e| e.to_string())
    }

    /// Read a `dimen` from the framework's `android` resource package (e.g.
    /// `status_bar_height`, `navigation_bar_height`) → physical px, or 0 if
    /// the identifier doesn't resolve on this device.
    fn framework_dimen(
        env: &mut jni::JNIEnv,
        res: &JObject,
        name: &str,
    ) -> Result<i32, jni::errors::Error> {
        let jname = env.new_string(name)?;
        let jtype = env.new_string("dimen")?;
        let jpkg = env.new_string("android")?;
        let id = env
            .call_method(
                res,
                "getIdentifier",
                "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I",
                &[
                    JValue::Object(&jname),
                    JValue::Object(&jtype),
                    JValue::Object(&jpkg),
                ],
            )?
            .i()?;
        if id <= 0 {
            return Ok(0);
        }
        env.call_method(res, "getDimensionPixelSize", "(I)I", &[JValue::Int(id)])?
            .i()
    }

    pub fn system_insets() -> Result<super::SystemInsets, String> {
        with_activity(|env, activity| {
            let res = env
                .call_method(activity, "getResources", "()Landroid/content/res/Resources;", &[])?
                .l()?;
            let top = framework_dimen(env, &res, "status_bar_height")?;
            let bottom = framework_dimen(env, &res, "navigation_bar_height")?;
            Ok(super::SystemInsets { top, bottom })
        })
    }

    /// Relaunch this app so its shared-storage sandbox re-mounts.
    ///
    /// We must start the new activity while we're still the foreground app —
    /// Android 10+ blocks background activity starts, so scheduling the relaunch
    /// for *after* we die (AlarmManager/PendingIntent) silently no-ops (the
    /// alarm fires with the app dead → the activity start is denied and nothing
    /// comes back). Instead: build a fresh-task restart intent
    /// (`Intent.makeRestartActivityTask`, which sets NEW_TASK|CLEAR_TASK),
    /// `startActivity` it now (allowed — we're foreground), give the system a
    /// beat to queue the transition, then exit. The pending activity relaunch
    /// forces a brand-new process, which is what re-mounts storage.
    pub fn restart_app() -> Result<(), String> {
        with_activity(|env, activity| {
            let pm = env
                .call_method(
                    activity,
                    "getPackageManager",
                    "()Landroid/content/pm/PackageManager;",
                    &[],
                )?
                .l()?;
            let pkg = env
                .call_method(activity, "getPackageName", "()Ljava/lang/String;", &[])?
                .l()?;
            let intent = env
                .call_method(
                    &pm,
                    "getLaunchIntentForPackage",
                    "(Ljava/lang/String;)Landroid/content/Intent;",
                    &[JValue::Object(&pkg)],
                )?
                .l()?;
            let comp = env
                .call_method(
                    &intent,
                    "getComponent",
                    "()Landroid/content/ComponentName;",
                    &[],
                )?
                .l()?;
            // Intent.makeRestartActivityTask(component) → NEW_TASK|CLEAR_TASK
            let restart_intent = env
                .call_static_method(
                    "android/content/Intent",
                    "makeRestartActivityTask",
                    "(Landroid/content/ComponentName;)Landroid/content/Intent;",
                    &[JValue::Object(&comp)],
                )?
                .l()?;
            env.call_method(
                activity,
                "startActivity",
                "(Landroid/content/Intent;)V",
                &[JValue::Object(&restart_intent)],
            )?;
            Ok(())
        })?;
        // Let the activity-start transition register before we tear the process
        // down; the queued relaunch then spawns a fresh process. Never returns.
        std::thread::sleep(std::time::Duration::from_millis(150));
        std::process::exit(0);
    }

    pub fn has_all_files_access() -> Result<bool, String> {
        with_activity(|env, _activity| {
            // Environment.isExternalStorageManager() — static, added in API 30.
            let result = env
                .call_static_method(
                    "android/os/Environment",
                    "isExternalStorageManager",
                    "()Z",
                    &[],
                )?
                .z()?;
            Ok(result)
        })
    }

    pub fn request_all_files_access() -> Result<(), String> {
        with_activity(|env, activity| {
            // Intent(Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION)
            let action = env.new_string(
                "android.settings.MANAGE_APP_ALL_FILES_ACCESS_PERMISSION",
            )?;
            let intent = env.new_object(
                "android/content/Intent",
                "(Ljava/lang/String;)V",
                &[JValue::Object(&action)],
            )?;

            // uri = Uri.parse("package:" + activity.getPackageName())
            let pkg = env
                .call_method(activity, "getPackageName", "()Ljava/lang/String;", &[])?
                .l()?;
            let pkg_str: String = env.get_string((&pkg).into())?.into();
            let uri_string = env.new_string(format!("package:{pkg_str}"))?;
            let uri = env
                .call_static_method(
                    "android/net/Uri",
                    "parse",
                    "(Ljava/lang/String;)Landroid/net/Uri;",
                    &[JValue::Object(&uri_string)],
                )?
                .l()?;
            env.call_method(
                &intent,
                "setData",
                "(Landroid/net/Uri;)Landroid/content/Intent;",
                &[JValue::Object(&uri)],
            )?;

            // activity.startActivity(intent)
            env.call_method(
                activity,
                "startActivity",
                "(Landroid/content/Intent;)V",
                &[JValue::Object(&intent)],
            )?;
            Ok(())
        })
    }
}
