name: "Setup System Dependencies"
description: "Installs GTK, WebKit, DBus, and Keyring build dependencies for Linux"

runs:
  using: "composite"
  steps:
    - name: Install Linux Packages
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update -q
        sudo apt-get install -y \
          libwebkit2gtk-4.1-dev \
          libappindicator3-dev \
          librsvg2-dev \
          patchelf \
          libssl-dev \
          libdbus-1-dev \
          dbus-x11 \
          gnome-keyring \
          xdg-utils \
          file \
          fuse \
          libfuse2t64
